
export const guestRoles = {
  "janay-marie": "food-part-1",
  "bola-akeju": "food-part-1",
  "sarabi": "food-part-1",
  "winifred-asante": "food-part-1",
  "zhane-paige": "food-part-1",
  "lara-grace-ilori": "food-part-1",
  "tito-mogaji": "food-part-1",
  "kodj": "food-part-1",
  "dalvin-james": "food-part-2",
  "zahira-odimayo": "food-part-2",
  "renee-binns": "food-part-2",
  "fee-mak": "food-part-2",
  "ndouri": "food-part-2",
  "mel-ijieh": "food-part-2",
  "gracelyn-achebo-awusu": "food-part-2",
  "jade-marie-arthur": "food-part-2",
  "tate-lolita": "food-part-2",
  "caitlin": "food-part-2",
  "henry": "bbq-contribution",
  "olu-qdex": "bbq-contribution",
  "sabrina-ansah": "bbq-contribution",
  "lea-barron": "bbq-contribution",
  "bernice-hughes": "bbq-contribution",
  "leroy-shabaka-pinder": "bbq-contribution",
  "hope-fashina": "bbq-contribution",
  "aleria": "bbq-contribution",
  "aiesha": "drinks",
  "wildat-hassan": "drinks",
  "doyin-ajiboye": "drinks",
  "seyi": "drinks",
  "michael-stay-wavey": "drinks",
  "jordan": "drinks",
  "chanice-cooke": "drinks"
};
